version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: "thursday"
    time: "14:00"
  assignees:
    - "@open-sauced/maintainers"
  reviewers:
    - "@open-sauced/maintainers"
  ignore:
    - dependency-name: "*"
      update-types: ["version-update:semver-major"]
    - dependency-name: "@storybook*"
    - dependency-name: "storybook*"
  open-pull-requests-limit: 15
  labels:
  - chore
  - dependencies
